## Word2Vec using gensim model

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from gensim.models import Word2Vec
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
import re

In [ ]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""      

In [ ]:
# Preprocessing the data
text = re.sub(r'\[[0-9]*\]',' ',paragraph)
text = re.sub(r'\s+',' ',text)
text = text.lower()
text = re.sub(r'\d',' ',text)
text = re.sub(r'\s+',' ',text)

In [ ]:
# Preparing the dataset
sentences = nltk.sent_tokenize(text)
sentences

['i have three visions for india.',
 'in years of our history, people from all over the world have come and invaded us, captured our lands, conquered our minds.',
 'from alexander onwards, the greeks, the turks, the moguls, the portuguese, the british, the french, the dutch, all of them came and looted us, took over what was ours.',
 'yet we have not done this to any other nation.',
 'we have not conquered anyone.',
 'we have not grabbed their land, their culture, their history and tried to enforce our way of life on them.',
 'why?',
 'because we respect the freedom of others.that is why my first vision is that of freedom.',
 'i believe that india got its first vision of this in , when we started the war of independence.',
 'it is this freedom that we must protect and nurture and build on.',
 'if we are not free, no one will respect us.',
 'my second vision for india’s development.',
 'for fifty years we have been a developing nation.',
 'it is time we see ourselves as a developed nati

In [ ]:
sentences = [nltk.word_tokenize(sentence) for sentence in sentences]
sentences

[['i', 'have', 'three', 'visions', 'for', 'india', '.'],
 ['in',
  'years',
  'of',
  'our',
  'history',
  ',',
  'people',
  'from',
  'all',
  'over',
  'the',
  'world',
  'have',
  'come',
  'and',
  'invaded',
  'us',
  ',',
  'captured',
  'our',
  'lands',
  ',',
  'conquered',
  'our',
  'minds',
  '.'],
 ['from',
  'alexander',
  'onwards',
  ',',
  'the',
  'greeks',
  ',',
  'the',
  'turks',
  ',',
  'the',
  'moguls',
  ',',
  'the',
  'portuguese',
  ',',
  'the',
  'british',
  ',',
  'the',
  'french',
  ',',
  'the',
  'dutch',
  ',',
  'all',
  'of',
  'them',
  'came',
  'and',
  'looted',
  'us',
  ',',
  'took',
  'over',
  'what',
  'was',
  'ours',
  '.'],
 ['yet',
  'we',
  'have',
  'not',
  'done',
  'this',
  'to',
  'any',
  'other',
  'nation',
  '.'],
 ['we', 'have', 'not', 'conquered', 'anyone', '.'],
 ['we',
  'have',
  'not',
  'grabbed',
  'their',
  'land',
  ',',
  'their',
  'culture',
  ',',
  'their',
  'history',
  'and',
  'tried',
  'to',
  'e

In [ ]:
for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]

In [ ]:
model = Word2Vec(sentences, min_count = 1, size = 300)

In [ ]:
words = model.wv.vocab
words

{'three': <gensim.models.keyedvectors.Vocab at 0x7f621e170210>,
 'visions': <gensim.models.keyedvectors.Vocab at 0x7f621dfa2ed0>,
 'india': <gensim.models.keyedvectors.Vocab at 0x7f621dfa2510>,
 '.': <gensim.models.keyedvectors.Vocab at 0x7f621dfa2a90>,
 'years': <gensim.models.keyedvectors.Vocab at 0x7f621df66dd0>,
 'history': <gensim.models.keyedvectors.Vocab at 0x7f621df66410>,
 ',': <gensim.models.keyedvectors.Vocab at 0x7f621df66310>,
 'people': <gensim.models.keyedvectors.Vocab at 0x7f621df38510>,
 'world': <gensim.models.keyedvectors.Vocab at 0x7f621dfa2bd0>,
 'come': <gensim.models.keyedvectors.Vocab at 0x7f621df66750>,
 'invaded': <gensim.models.keyedvectors.Vocab at 0x7f621df38790>,
 'us': <gensim.models.keyedvectors.Vocab at 0x7f621df3a490>,
 'captured': <gensim.models.keyedvectors.Vocab at 0x7f621df3a7d0>,
 'lands': <gensim.models.keyedvectors.Vocab at 0x7f621df3a250>,
 'conquered': <gensim.models.keyedvectors.Vocab at 0x7f621df3ab10>,
 'minds': <gensim.models.keyedvectors.

In [ ]:
vector = model.wv['war']
vector

array([-1.00765683e-04,  5.11345297e-06, -5.69130701e-04, -1.00073509e-03,
       -1.18172762e-03,  4.34233749e-04,  1.39824487e-03, -5.06973010e-04,
        1.42952392e-03,  8.68626172e-04,  1.62253412e-03,  1.26817392e-03,
        1.49028457e-03, -1.05421990e-03, -1.40975812e-03,  1.21331704e-03,
        2.64299451e-04,  9.71271482e-04,  1.53099187e-03, -3.87206266e-04,
        1.59890088e-03,  8.36082792e-04, -1.40540721e-03, -5.47851727e-04,
        1.04382588e-03, -3.57517332e-04,  5.45460323e-04, -1.07018801e-04,
        1.03638915e-03,  1.43126433e-03,  1.01535104e-03,  1.47001341e-03,
        1.40386785e-03,  1.45369431e-03,  2.35161846e-04,  2.00433409e-04,
        1.18233927e-03, -2.36567343e-04, -1.64819602e-03, -6.07432274e-04,
       -3.20807390e-04,  4.50779742e-04,  1.64581672e-03,  1.01323891e-03,
       -4.16703202e-04, -1.54352572e-03, -9.69073590e-05,  1.24202634e-03,
       -7.14835827e-04,  4.74112720e-04, -5.96152851e-04,  9.69291781e-04,
        1.52245013e-03, -

In [ ]:
len(vector)

300

In [ ]:
similar = model.wv.most_similar('strength')
similar

[('growth', 0.12095004320144653),
 ('today', 0.1101575493812561),
 ('career', 0.10803128033876419),
 ('grabbed', 0.08832622319459915),
 ('self-reliant', 0.08729952573776245),
 ('development', 0.08059138059616089),
 ('achievements', 0.07856708019971848),
 ('?', 0.06086750328540802),
 ('invaded', 0.058910876512527466),
 ('moguls', 0.055284030735492706)]

## Word Embedding using Embedding layers in keras

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
### Vocabulary size
voc_size=10000

In [ ]:
onehot_repr = [one_hot(words, 1000) for words in sent]

In [ ]:
onehot_repr

[[145, 112, 188, 835],
 [145, 112, 188, 255],
 [145, 231, 188, 876],
 [840, 414, 281, 838, 66],
 [840, 414, 281, 838, 491],
 [781, 145, 547, 188, 822],
 [498, 954, 566, 838]]

## Word Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs =pad_sequences(onehot_repr, padding='post', maxlen = sent_length)
embedded_docs

array([[145, 112, 188, 835,   0,   0,   0,   0],
       [145, 112, 188, 255,   0,   0,   0,   0],
       [145, 231, 188, 876,   0,   0,   0,   0],
       [840, 414, 281, 838,  66,   0,   0,   0],
       [840, 414, 281, 838, 491,   0,   0,   0],
       [781, 145, 547, 188, 822,   0,   0,   0],
       [498, 954, 566, 838,   0,   0,   0,   0]], dtype=int32)

In [ ]:
dim = 10
model = Sequential([
    Embedding(voc_size, dim, input_length = sent_length)
])

model.compile('adam', 'mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
predicted_word2vec = model.predict(embedded_docs)
predicted_word2vec

array([[[ 0.01242032,  0.03884274, -0.0474635 , -0.02519589,
          0.04214012, -0.00812836,  0.00741267, -0.02490288,
          0.03063056, -0.02343127],
        [ 0.02694694,  0.03384146, -0.01086465, -0.00214516,
          0.0158315 , -0.00390663, -0.01582213, -0.04420561,
          0.01934833,  0.01967248],
        [-0.03432773, -0.01311249, -0.04548964,  0.02315657,
         -0.04971747,  0.04806087, -0.00019454, -0.00113721,
          0.00010075,  0.02080795],
        [ 0.02610346,  0.00078497, -0.0151526 ,  0.04682631,
          0.04851611,  0.02121432, -0.03883206,  0.03246036,
         -0.02839024,  0.04828945],
        [-0.03752302,  0.02704081, -0.02650355,  0.02687594,
         -0.03812734, -0.02728409,  0.03373425, -0.03609958,
          0.0480235 ,  0.02370424],
        [-0.03752302,  0.02704081, -0.02650355,  0.02687594,
         -0.03812734, -0.02728409,  0.03373425, -0.03609958,
          0.0480235 ,  0.02370424],
        [-0.03752302,  0.02704081, -0.02650355,  0.0

In [ ]:
embedded_docs[0]

array([145, 112, 188, 835,   0,   0,   0,   0], dtype=int32)

In [ ]:
predicted_word2vec[0]

array([[ 0.01242032,  0.03884274, -0.0474635 , -0.02519589,  0.04214012,
        -0.00812836,  0.00741267, -0.02490288,  0.03063056, -0.02343127],
       [ 0.02694694,  0.03384146, -0.01086465, -0.00214516,  0.0158315 ,
        -0.00390663, -0.01582213, -0.04420561,  0.01934833,  0.01967248],
       [-0.03432773, -0.01311249, -0.04548964,  0.02315657, -0.04971747,
         0.04806087, -0.00019454, -0.00113721,  0.00010075,  0.02080795],
       [ 0.02610346,  0.00078497, -0.0151526 ,  0.04682631,  0.04851611,
         0.02121432, -0.03883206,  0.03246036, -0.02839024,  0.04828945],
       [-0.03752302,  0.02704081, -0.02650355,  0.02687594, -0.03812734,
        -0.02728409,  0.03373425, -0.03609958,  0.0480235 ,  0.02370424],
       [-0.03752302,  0.02704081, -0.02650355,  0.02687594, -0.03812734,
        -0.02728409,  0.03373425, -0.03609958,  0.0480235 ,  0.02370424],
       [-0.03752302,  0.02704081, -0.02650355,  0.02687594, -0.03812734,
        -0.02728409,  0.03373425, -0.03609958

In [ ]:
predicted_word2vec[1]

array([[ 0.01242032,  0.03884274, -0.0474635 , -0.02519589,  0.04214012,
        -0.00812836,  0.00741267, -0.02490288,  0.03063056, -0.02343127],
       [ 0.02694694,  0.03384146, -0.01086465, -0.00214516,  0.0158315 ,
        -0.00390663, -0.01582213, -0.04420561,  0.01934833,  0.01967248],
       [-0.03432773, -0.01311249, -0.04548964,  0.02315657, -0.04971747,
         0.04806087, -0.00019454, -0.00113721,  0.00010075,  0.02080795],
       [-0.0276776 , -0.04052113,  0.02950193,  0.02044245, -0.0167946 ,
         0.03351877, -0.03767474,  0.00356825, -0.01800897, -0.03624994],
       [-0.03752302,  0.02704081, -0.02650355,  0.02687594, -0.03812734,
        -0.02728409,  0.03373425, -0.03609958,  0.0480235 ,  0.02370424],
       [-0.03752302,  0.02704081, -0.02650355,  0.02687594, -0.03812734,
        -0.02728409,  0.03373425, -0.03609958,  0.0480235 ,  0.02370424],
       [-0.03752302,  0.02704081, -0.02650355,  0.02687594, -0.03812734,
        -0.02728409,  0.03373425, -0.03609958