In [3]:
import joblib

In [11]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from gensim.models import Word2Vec
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Preprocessing can be found in news_model : Probabilistic Language Model

In [16]:
from tqdm import tqdm

In [4]:
tokenized_sentences = joblib.load("/content/drive/MyDrive/Colab Notebooks/NLP/Language Modelling/Datasets/Nepali_Corpus/tokenized_sentences.pkl")

In [10]:
len(tokenized_sentences)

198000

In [8]:
print(tokenized_sentences[0])

['मकवानपुर', 'फिल्म', 'हुर्रेले', 'रिलिज', 'मिति', 'नजिकिएसँगै', 'प्रचारप्रसारमा', 'तीव्रता', 'दिएको', 'छ']


In [9]:
print(tokenized_sentences[1])

['शनिबार', 'हेटौंडा', 'आइपुगेको', 'फिल्मको', 'निर्माता', 'तथा', 'कलाकारको', 'टोलीले', 'फिल्म', 'हास्यप्रधान', 'रहे', 'पनि', 'पृथक', 'कथाबस्तुमा', 'निर्माण', 'रहेको', 'बताए']


In [12]:
print(stopwords.words('nepali'))

['छ', 'र', 'पनि', 'छन्', 'लागि', 'भएको', 'गरेको', 'भने', 'गर्न', 'गर्ने', 'हो', 'तथा', 'यो', 'रहेको', 'उनले', 'थियो', 'हुने', 'गरेका', 'थिए', 'गर्दै', 'तर', 'नै', 'को', 'मा', 'हुन्', 'भन्ने', 'हुन', 'गरी', 'त', 'हुन्छ', 'अब', 'के', 'रहेका', 'गरेर', 'छैन', 'दिए', 'भए', 'यस', 'ले', 'गर्नु', 'औं', 'सो', 'त्यो', 'कि', 'जुन', 'यी', 'का', 'गरि', 'ती', 'न', 'छु', 'छौं', 'लाई', 'नि', 'उप', 'अक्सर', 'आदि', 'कसरी', 'क्रमशः', 'चाले', 'अगाडी', 'अझै', 'अनुसार', 'अन्तर्गत', 'अन्य', 'अन्यत्र', 'अन्यथा', 'अरु', 'अरुलाई', 'अर्को', 'अर्थात', 'अर्थात्', 'अलग', 'आए', 'आजको', 'ओठ', 'आत्म', 'आफू', 'आफूलाई', 'आफ्नै', 'आफ्नो', 'आयो', 'उदाहरण', 'उनको', 'उहालाई', 'एउटै', 'एक', 'एकदम', 'कतै', 'कम से कम', 'कसै', 'कसैले', 'कहाँबाट', 'कहिलेकाहीं', 'का', 'किन', 'किनभने', 'कुनै', 'कुरा', 'कृपया', 'केही', 'कोही', 'गए', 'गरौं', 'गर्छ', 'गर्छु', 'गर्नुपर्छ', 'गयौ', 'गैर', 'चार', 'चाहनुहुन्छ', 'चाहन्छु', 'चाहिए', 'छू', 'जताततै', 'जब', 'जबकि', 'जसको', 'जसबाट', 'जसमा', 'जसलाई', 'जसले', 'जस्तै', 'जस्तो', 'जस्तोसुकै', 'जहाँ'

In [17]:
# removing the stop-words
for i in tqdm(range(len(tokenized_sentences))):
  tokenized_sentences[i] = [word for word in tokenized_sentences[i] if word not in stopwords.words('nepali')]

100%|██████████| 198000/198000 [07:53<00:00, 418.26it/s]


In [18]:
print(tokenized_sentences[0])
print(tokenized_sentences[1])

['मकवानपुर', 'फिल्म', 'हुर्रेले', 'रिलिज', 'मिति', 'नजिकिएसँगै', 'प्रचारप्रसारमा', 'तीव्रता', 'दिएको']
['शनिबार', 'हेटौंडा', 'आइपुगेको', 'फिल्मको', 'निर्माता', 'कलाकारको', 'टोलीले', 'फिल्म', 'हास्यप्रधान', 'रहे', 'पृथक', 'कथाबस्तुमा', 'निर्माण', 'बताए']


# Word2Vec

In [33]:
model = Word2Vec(tokenized_sentences, min_count = 100, size = 300)

### Saving and Loading the model

In [135]:
model.save("/content/drive/MyDrive/Colab Notebooks/NLP/Language Modelling/Word Embeddings/new_model_vec.model")

In [136]:
model = Word2Vec.load("/content/drive/MyDrive/Colab Notebooks/NLP/Language Modelling/Word Embeddings/new_model_vec.model")

In [137]:
words = model.wv.vocab
print(type(words))

<class 'dict'>


In [138]:
len(words)

3312

In [36]:
index = 0
for key, value in words.items():
  if index > 5:
    break
  print(key, value)
  index +=1

फिल्म Vocab(count:1604, index:101, sample_int:4294967296)
रिलिज Vocab(count:321, index:1030, sample_int:4294967296)
मिति Vocab(count:276, index:1220, sample_int:4294967296)
दिएको Vocab(count:2128, index:62, sample_int:4294967296)
शनिबार Vocab(count:675, index:403, sample_int:4294967296)
आइपुगेको Vocab(count:106, index:3086, sample_int:4294967296)


In [37]:
def getVector(word, model):
  return model.wv[word]

In [38]:
vector = getVector("फिल्म", model)
vector

array([-6.20833576e-01,  1.26247972e-01,  1.42318979e-01, -2.00702444e-01,
        2.69383878e-01, -5.57905994e-02, -7.45955586e-01,  2.01863214e-01,
        2.77698855e-03, -1.33984357e-01,  2.46328801e-01,  8.18838060e-01,
       -6.05572062e-03,  2.99484819e-01,  7.54973769e-01,  1.08610642e+00,
       -6.60841092e-02,  5.82475781e-01, -1.84294775e-01,  1.85571671e-01,
        3.62526894e-01,  4.31614727e-01, -3.23227376e-01, -2.73096561e-01,
        1.85198382e-01, -1.01791739e+00, -7.05631435e-01,  8.77372503e-01,
        5.05810976e-01, -5.19497454e-01, -3.67790610e-01, -7.85559192e-02,
       -5.01882434e-01,  4.35184479e-01, -2.84609109e-01,  1.38479099e-01,
        5.28576225e-02,  1.01035446e-01,  1.17066652e-01, -3.29045579e-03,
       -2.54846066e-01, -2.46951103e-01, -2.88740486e-01, -4.45806146e-01,
        3.82404625e-01, -2.28403419e-01, -1.52907399e-02, -1.89155504e-01,
        1.26451954e-01, -1.35942906e-01,  5.25022969e-02,  5.78167498e-01,
       -3.77741188e-01,  

In [39]:
similar = model.wv.most_similar('फिल्म')
similar

[('फिल्मको', 0.8686474561691284),
 ('सिनेमा', 0.8001838326454163),
 ('फिल्मलाई', 0.7860930562019348),
 ('गीत', 0.7643048763275146),
 ('रिलिज', 0.7267906069755554),
 ('फिल्ममा', 0.7185119390487671),
 ('फिल्मले', 0.7175328731536865),
 ('फिल्मका', 0.6980116963386536),
 ('गीतको', 0.687585711479187),
 ('दर्शकले', 0.6624289751052856)]

# 3D Word2Vev Visualization

In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

%matplotlib inline

In [81]:
vocab = []
for key, value in words.items():
  vocab.append(key)

In [82]:
len(vocab)

3312

In [83]:
vocab[0:5]

['फिल्म', 'रिलिज', 'मिति', 'दिएको', 'शनिबार']

In [84]:
vectors = []
for word in vocab:
  vectors.append(model.wv[word])

In [85]:
len(vectors)

3312

In [86]:
print(vectors[0])

[-6.20833576e-01  1.26247972e-01  1.42318979e-01 -2.00702444e-01
  2.69383878e-01 -5.57905994e-02 -7.45955586e-01  2.01863214e-01
  2.77698855e-03 -1.33984357e-01  2.46328801e-01  8.18838060e-01
 -6.05572062e-03  2.99484819e-01  7.54973769e-01  1.08610642e+00
 -6.60841092e-02  5.82475781e-01 -1.84294775e-01  1.85571671e-01
  3.62526894e-01  4.31614727e-01 -3.23227376e-01 -2.73096561e-01
  1.85198382e-01 -1.01791739e+00 -7.05631435e-01  8.77372503e-01
  5.05810976e-01 -5.19497454e-01 -3.67790610e-01 -7.85559192e-02
 -5.01882434e-01  4.35184479e-01 -2.84609109e-01  1.38479099e-01
  5.28576225e-02  1.01035446e-01  1.17066652e-01 -3.29045579e-03
 -2.54846066e-01 -2.46951103e-01 -2.88740486e-01 -4.45806146e-01
  3.82404625e-01 -2.28403419e-01 -1.52907399e-02 -1.89155504e-01
  1.26451954e-01 -1.35942906e-01  5.25022969e-02  5.78167498e-01
 -3.77741188e-01  1.40763238e-01  4.67610329e-01  7.38423988e-02
 -7.07642317e-01  3.27971250e-01  4.47251767e-01  3.71709228e-01
 -4.24237311e-01  4.67156

In [87]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 3)
vector_transformed = pca.fit(vectors)
vector_3d = pca.transform(vectors)


In [88]:
len(vector_3d)

3312

In [89]:
vector_3d[0]

array([ 1.63287597, -2.01331772,  2.3965658 ])

In [125]:
x, y, z = [], [], []
for vector in vector_3d:
  x.append(vector[0])
  y.append(vector[1])
  z.append(vector[2])

In [127]:
zipped = list(zip(vocab, x, y, z))

In [128]:
zipped[0:5]

[('फिल्म', 1.6328759739149232, -2.0133177237409354, 2.396565795401461),
 ('रिलिज', 2.0920267040205025, 0.1864986836890963, 2.7732963110824684),
 ('मिति', 1.3811404149153046, 0.7649409974065926, -0.6041011673631563),
 ('दिएको', -0.3401851020797366, 0.844930518533489, -0.8713144062246357),
 ('शनिबार', 3.622708396345035, 1.6262405849428547, 1.3119205096601356)]

In [129]:
df_3d = pd.DataFrame(zipped[0:50], columns=["vocab", "x", "y", "z"])
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      4 non-null      object
 1   Age       4 non-null      int64 
 2   Location  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes
None


In [131]:
df_3d.head()

vocab         x         y         z
0   फिल्म  1.632876 -2.013318  2.396566
1   रिलिज  2.092027  0.186499  2.773296
2    मिति  1.381140  0.764941 -0.604101
3   दिएको -0.340185  0.844931 -0.871314
4  शनिबार  3.622708  1.626241  1.311921

In [134]:
fig = px.scatter_3d(df_3d, x='x', y='y', z='z', text = "vocab")
fig.show()

# 2D Word2Vev Visualization

In [105]:
vocab[0:5]

['फिल्म', 'रिलिज', 'मिति', 'दिएको', 'शनिबार']

In [107]:
vectors[0]

array([-6.20833576e-01,  1.26247972e-01,  1.42318979e-01, -2.00702444e-01,
        2.69383878e-01, -5.57905994e-02, -7.45955586e-01,  2.01863214e-01,
        2.77698855e-03, -1.33984357e-01,  2.46328801e-01,  8.18838060e-01,
       -6.05572062e-03,  2.99484819e-01,  7.54973769e-01,  1.08610642e+00,
       -6.60841092e-02,  5.82475781e-01, -1.84294775e-01,  1.85571671e-01,
        3.62526894e-01,  4.31614727e-01, -3.23227376e-01, -2.73096561e-01,
        1.85198382e-01, -1.01791739e+00, -7.05631435e-01,  8.77372503e-01,
        5.05810976e-01, -5.19497454e-01, -3.67790610e-01, -7.85559192e-02,
       -5.01882434e-01,  4.35184479e-01, -2.84609109e-01,  1.38479099e-01,
        5.28576225e-02,  1.01035446e-01,  1.17066652e-01, -3.29045579e-03,
       -2.54846066e-01, -2.46951103e-01, -2.88740486e-01, -4.45806146e-01,
        3.82404625e-01, -2.28403419e-01, -1.52907399e-02, -1.89155504e-01,
        1.26451954e-01, -1.35942906e-01,  5.25022969e-02,  5.78167498e-01,
       -3.77741188e-01,  

In [110]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
vector_transformed = pca.fit(vectors)
vector_2d = pca.transform(vectors)

In [112]:
x, y = [], []
for vector in vector_2d:
  x.append(vector[0])
  y.append(vector[1])

In [117]:
zipped = list(zip(vocab, x, y))
df_2d = pd.DataFrame(zipped[:100], columns = ["vocab", "x", "y"])

In [122]:
fig = px.scatter(df_2d, x = "x", y = "y", hover_data = ["vocab"], text = "vocab")
fig.update_traces(textposition="bottom right")
fig.show()